site_name: Enhanced Commands Mod Docs
theme:
  name: material
  palette:
    # 自动模式的调色板切换
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: 切换到明亮模式

    # 明亮模式的调色板切换
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 切换到黑暗模式

    # 黑暗模式的调色板切换
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换到系统偏好
  
  language: zh
  locale: zh
  features:
    - navigation.indexes
    - toc.integrate 
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.follow
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.action.view
    - content.action.edit

plugins:
  - search
  - awesome-nav
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          site_name: 增强命令模组文档
          default: true
          name: 简体中文
          build: true
          copyright: 请注意：本网站目前仍在测试。
          fixed_link: true
          nav_translations:
            Home: 主页
            Arguments: 参数
            Commands: 命令
            Curve: 曲线
            Block function: 方块函数
            Block predicate: 方块谓词
            Entity predicate: 实体谓词
            Item function: 物品函数
            Item predicate: 物品谓词
            Mod configs: 模组配置
            NBT function: NBT 函数
            NBT predicate: NBT 谓词
            Region: 区域
            '/if and /unless': '/if 和 /unless'
          admonition_translations:
            - note: 注意
            - warning: 警告
            - tip: 提示
            - example: 示例
            - danger: 危险
            - success: 成功
            - failure: 失败
            - question: 问题
            - quote: 引用
        - locale: en
          name: English
          build: true
          fixed_link: true
copyright: 'Note: The website is currently under test.'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - stylesheets/style.css

watch:
  - includes

repo_url: https://github.com/SolidBlock-cn/enhanced_commands_mod_docs
edit_uri: edit/main/docs/
